spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8000